---
abstract: 'dbic component generating accessors method to get data by a table pointing to a Lookup table (catalog of terms) in a efficient way (cache system)'
author:
  - '[Karl Forner <karl.forner@gmail.com>, thomas Rubattel <rubattel@cpan.org>]'
build_requires:
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  DDP: 0
  Module::Build: 0.3601
  Moose: 0
  Test::DBIx::Class: 0
  Test::Exception: 0
  Test::More: 0
  perl: v5.14.2
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300025, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-LookupColumn
requires:
  Carp: 0
  Class::MOP: 0
  DBIx::Class: 0
  Data::Dumper: 0
  Hash::Merge::Simple: 0
  Smart::Comments: 0
  base: 0
  strict: 0
  warnings: 0
version: 0.06
